name: Generate Random Password
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate password
        id: genpass
        uses: ./.github/actions/generate-password
      - name: Show password
        run: |
          echo "Generated password: ${{ steps.genpass.outputs.password }}"
